### ISSUE TITLE
Fail to build app with the new default android platform - android@4.0.0

### ISSUE THREAD

**Issue by Honry** [cranberrygame/phonegap-plugin-ad-admob#9]
Updated Cordova CLI to 5.0.0. When build the app with this plugin I get an error:

/home/lei/work/workspace/cordova/cordova-4.0/ad/platforms/android/src/com/cranberrygame/phonegap/plugin/ad/Admob.java:468: cannot find symbol
symbol  : method addView(android.widget.RelativeLayout)
location: interface org.apache.cordova.CordovaWebView
                        webView.addView(bannerViewLayout);
                               ^
warning: com/google/android/gms/ads/AdRequest$Builder.class(com/google/android/gms/ads:AdRequest$Builder.class): major version 51 is newer than 50, the highest major version supported by this compiler.
It is recommended that the compiler be upgraded.
warning: android/content/ContentResolver.class(android/content:ContentResolver.class): major version 51 is newer than 50, the highest major version supported by this compiler.
It is recommended that the compiler be upgraded.
warning: android/provider/Settings$Secure.class(android/provider:Settings$Secure.class): major version 51 is newer than 50, the highest major version supported by this compiler.
It is recommended that the compiler be upgraded.
warning: android/provider/Settings$NameValueTable.class(android/provider:Settings$NameValueTable.class): major version 51 is newer than 50, the highest major version supported by this compiler.
It is recommended that the compiler be upgraded.
/home/lei/work/workspace/cordova/cordova-4.0/ad/platforms/android/src/com/cranberrygame/phonegap/plugin/ad/Admob.java:579: cannot find symbol
symbol  : method getParent()
location: interface org.apache.cordova.CordovaWebView
                        ViewGroup parentView = (ViewGroup)webView.getParent();
                                                                 ^
warning: java/util/List.class(java/util:List.class): major version 51 is newer than 50, the highest major version supported by this compiler.
It is recommended that the compiler be upgraded.
Note: /home/lei/work/workspace/cordova/cordova-4.0/ad/platforms/android/src/com/cranberrygame/phonegap/plugin/ad/Admob.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
3 errors
96 warnings
:compileDebugJava FAILED
 
FAILURE: Build failed with an exception.
 
* What went wrong:
Execution failed for task ':compileDebugJava'.
> Compilation failed; see the compiler error output for details.
 
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
 
BUILD FAILED

**Comment by Honry** [comment]
Reference link: https://issues.apache.org/jira/browse/CB-9032

**Comment by cranberrygame** [comment]
@Honry 

Fixed cordova 5 build issue.

Thanks
Sang Ki Kwon

**Comment by Honry** [comment]
Many thanks @cranberrygame, it works now!
